version: '3'
services:
  websockets:
    build: .
    container_name: websockets
    restart: always
    ports:
      - 8765:8765
    volumes:
      - .:/app
    entrypoint: /app/entrypoint.sh
    networks:
      - proxynet


networks:
  proxynet:
    name: otpay_network